### PR TITLE
Test with more versions

### PR DESCRIPTION
**Pull request by winniehell**
I don't know about `0.11` but io.js would be nice.

### CODE REVIEW

**Comment by winniehell** [comment]
I think it makes sense to combine this with #20. For more :rocket:

**Comment by aseemk** [comment]
+1 for io.js, thanks! Let's take out 0.11 though; it's both unstable and obsolete now that 0.12 has shipped.

Thanks for all your PRs, btw! Sorry I'm a bit busy right now, but will get to the rest soon. =)

**Comment by winniehell** [comment]
I amended the commit and removed node.js `0.11`.

I also added two io.js versions explicitly (first and current) because `iojs` always points to the current stable release and for me it seems to be of interest if the tests fail for a specific release.

**Comment by aseemk** [comment]
Interesting, thanks. A couple of q's:
- Currently, `iojs` is redundant with `iojs-v1.8`. So do you just have `iojs` for the future?
- That made me wonder why we don't do that with `node` as well. I think the reason is Node upgrades are far less frequent, so it's not as big a deal.

==> Since io.js upgrades more frequently, and is in v1 semver mode, WDYT of simply `iojs-v1` for now, and we can add `iojs-v2` whenever it's out?

**Comment by winniehell** [comment]
I would try to answer two questions with the chosen versions:
- What node.js / io.js versions are supported?
- Does the code work with the most recent version / the upcoming release?

The first question is of interest for people who are considering to use `express-streamline` and have a fixed node.js / io.js version given. I would therefore pick a reasonable amount of different versions ranging from minimum supported version to current stable. In case of node.js that would be 0.8 to 0.12 right now and the huge number of stable releases in between. ;-) For io.js on the other hand the supported versions range from 1.0 to 1.8. Since they are very close in time I did not pick any other version in the range. I can not tell how close they are in terms of features.

To answer the second question, I added the `iojs` placeholder for the current stable release. As soon as that changes to a new version, tests will use it without further modification of the configuration file. With the same argument, I could add `stable` for node.js (or even `unstable`?).

What do you think? I know that `iojs` and `stable` are redundant for now. But they come in handy if you do not keep track of the most recent stable release (I don't).

**Comment by winniehell** [comment]
EDIT: Made a new pull request #26 to fix the build.

**Comment by winniehell** [comment]
https://github.com/aseemk/express-streamline/issues/28

**Pull request closed without merging**
